# Generated by Django 5.0.4 on 2024-04-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
